# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.16.0
_src_path: gh:radio-aktywne/template-app-litestar
accountname: radio-aktywne
appname: emirecords
description: Emission recording 🎥
docs: true
docsurl: https://radio-aktywne.github.io/app-emirecords
email: it@radioaktywne.pl
envprefix: EMIRECORDS
events: false
imagename: apps/emirecords
importname: emirecords
port: 31000
registry: true
releases: true
reponame: app-emirecords
repourl: https://github.com/radio-aktywne/app-emirecords
