services:
  emirecords:
    build:
      context: ./
      network: host
    environment:
      - "EMIRECORDS__SERVER__HOST=${EMIRECORDS__SERVER__HOST:-0.0.0.0}"
      - "EMIRECORDS__SERVER__PORT=${EMIRECORDS__SERVER__PORT:-31000}"
      - "EMIRECORDS__SERVER__TRUSTED=${EMIRECORDS__SERVER__TRUSTED:-*}"
      - "EMIRECORDS__EMISHOWS__HTTP__SCHEME=${EMIRECORDS__EMISHOWS__HTTP__SCHEME:-http}"
      - "EMIRECORDS__EMISHOWS__HTTP__HOST=${EMIRECORDS__EMISHOWS__HTTP__HOST:-localhost}"
      - "EMIRECORDS__EMISHOWS__HTTP__PORT=${EMIRECORDS__EMISHOWS__HTTP__PORT:-35000}"
      - "EMIRECORDS__EMISHOWS__HTTP__PATH=${EMIRECORDS__EMISHOWS__HTTP__PATH:-}"
      - "EMIRECORDS__MEDIARECORDS__S3__SECURE=${EMIRECORDS__MEDIARECORDS__S3__SECURE:-false}"
      - "EMIRECORDS__MEDIARECORDS__S3__HOST=${EMIRECORDS__MEDIARECORDS__S3__HOST:-localhost}"
      - "EMIRECORDS__MEDIARECORDS__S3__PORT=${EMIRECORDS__MEDIARECORDS__S3__PORT:-30000}"
      - "EMIRECORDS__MEDIARECORDS__S3__USER=${EMIRECORDS__MEDIARECORDS__S3__USER:-readwrite}"
      - "EMIRECORDS__MEDIARECORDS__S3__PASSWORD=${EMIRECORDS__MEDIARECORDS__S3__PASSWORD:-password}"
      - "EMIRECORDS__DEBUG=${EMIRECORDS__DEBUG:-false}"
    network_mode: host
